### ISSUE TITLE
Using masonic in nextjs

### ISSUE THREAD

**Issue by Lantianyou** [jaredLunde/masonic#173]
According to this reddit page, seems quite a lots of hook will cause issuse using nextjs, and there is no work around. https://www.reddit.com/r/nextjs/comments/1bhfikg/window_is_not_defined_error_in_nextjs_14_app/

**Comment by Lantianyou** [comment]
In my case
```
eferenceError: ResizeObserver is not defined
    at useResizeObserver (components/ui/useResizeObserver.ts:11:4)
    at Masonry (components/ui/masonry.tsx:103:47)
   9 |   const [forceUpdate] = useForceUpdate()
  10 |   const resizeObserver = createResizeObserver(
> 11 |     positioner,
```

**Comment by jaredLunde** [comment]
It doesn't make sense to render this component on the server. Simply put, it needs a browser window. 

https://github.com/jaredLunde/masonic/issues/123

**Comment by Lantianyou** [comment]
Yes, sure, the component throws an error anyway despite using "use client" directive. Cause all client component code are still run in ssr. As per the reddit post

**Comment by jaredLunde** [comment]
Use a dynamic import

**Comment by Lantianyou** [comment]
I understand, but dynamic import only work for component, not for hooks. So for hooks like `useResizeObserver`, still will throw error on server side

**Comment by Lantianyou** [comment]
Understood it. Also appreciate your answer. Just here to state the problem, it will cause error in nextjs server. Guess one day nextjs will fix it.

**Comment by biowaffeln** [comment]
You can wrap it in a `ClientOnly` component to make sure it's doesn't run during SSR. Here's one from `remix-utils`, should probably work in Next.js as well:
https://github.com/sergiodxa/remix-utils/blob/main/src/react/client-only.tsx

**Comment by Vito-Ethan** [comment]
For anyone using Next.js don't use the remix-utils solution. You should instead [dynamically import](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#with-named-exports) a named export and turn SSR off. This way the component only loads on the browser. For example:
```javascript
const Masonry: ComponentType<MasonryProps<TheTypeOfYourDataPassedToItems>> = dynamic(
    () => import('masonic').then((mod) => mod.Masonry),
    { ssr: false },
  );
```
